[package]
name = "sonar"
version = "0.1.0"
edition = "2024"

[dependencies]
logger = { path = "logger" }
version = { path = "version" }
icmp = { path = "icmp" }

clap = { version = "4.5.35", features = [ "derive" ] }
ctrlc = "3.4.6"
colored = "3.0.0"

[lints.clippy]
needless_return = "allow"