[package]
name = "icmp"
version = "0.1.0"
edition = "2024"

[dependencies]
fastrand = "2.3.0"
byteorder = "1.5.0"
socket2 = { version = "0.5.9", features = [ "all" ] }

logger = { path = "../logger" }